Entrega Practica 1 / Mosquera y Arenas
zahydo/labisii2021.2 pull request #2
Opened 2021-10-27 17:03 UTC by miguemm

2021-11-02 02:00 UTC, zahydo requested changes
1. Agregar un README para la práctica, en donde se describa cómo se corren las pruebas y cómo se ejecuta el proyecto.
2. El proyecto debe poder ejecutarse y correr las pruebas haciendo uso únicamente de la CLI. Usar Maven para este propósito.
3. Poner en NOMBRE/README.md el grupo al que pertenece

2021-11-02 16:08 UTC, miguemm commented
Correccion antes mencionadas

2021-11-03 13:43 UTC, miguemm commented
Estimado profe, nuestra rama ya hizo las correcciones y estamos listos para revicion @zahydo

2021-11-03 14:02 UTC, zahydo approved these changes
Well done

2021-11-03 14:02 UTC, merged